BOOKS/Models/Huazimi.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BOOKS.Models
{
    public class Huazimi
    {
        public int id { get; set; }
        public DateTime DataPritjes { get; set; }
        public DateTime DataKthimit { get; set; }
        public int Klienti_id { get; set; }
        public int Libra_id { get; set; }
        public bool Aktiv { get; set; }

    }
}

BOOKS/Controllers/HuazimiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BOOKS.Models;
using BOOKS.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Mail;

namespace BOOKS.Controllers
{
    public class HuazimiController : Controller
    {
        // GET: HuazimiController
        private readonly ApplicationDbContext _context;

        public HuazimiController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        { 
            var huazimet = from s in _context.Huazimi
                             select s;

            int pageSize = 20;
            return View(await PaginatedList<Huazimi>.CreateAsync(huazimet.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: HuazimiController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var huazimi = await _context.Huazimi
                .FirstOrDefaultAsync(m => m.id == id);

            if (huazimi == null)
            {
                return NotFound();
            }

            return View(huazimi);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.klientetid = _context.Klienti.Where(k => k.Aktiv==true).ToList();
            var librat = _context.Books.Where(l => l.E_Lire == true).ToList();
            ViewBag.libraid = librat;
            return View(); 

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DataKthimit,Klienti_id,Libra_id,")] Huazimi huazimi)
        {
            try { 
                if (ModelState.IsValid)
                        {
                            huazimi.DataPritjes = DateTime.Now.AddMonths(1);
                            huazimi.Aktiv = true;
                             _context.Huazimi.Add(huazimi);
                            Book libri = _context.Books.Where(t => t.id == huazimi.Libra_id).First();
                            libri.E_Lire = false;
                            libri.huazime++;
                             _context.Books.Update(libri);
                    await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));
                        }
                    }
                    catch (DbUpdateException /* ex */)
                    {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                            "Try again, and if the problem persists " +
                            "see your system administrator.");
                    }
                    return View(huazimi);

                }

        public IActionResult Kthe(int id)
        {
            Huazimi huazimi = _context.Huazimi.Where(t => t.id == id).First();
            huazimi.DataKthimit = DateTime.Now;
            huazimi.Aktiv = false;
            _context.Huazimi.Update(huazimi);
            _context.SaveChanges();


            Book libri = _context.Books.Where(t => t.id == huazimi.Libra_id).First();
            libri.E_Lire = true;
            _context.Books.Update(libri);
            _context.SaveChanges();
            var rez = _context.Rezervimi.Where(r => r.Aktiv == true).ToList();
            foreach (Rezervimi r in rez)
            {
                if(huazimi.Libra_id == r.Libra_id)
                {
                    var klienti = _context.Klienti.Where(k => k.id == r.Klienti_id).First();
                    var libra = _context.Books.Where(k => k.id == r.Libra_id).First();
                    MailMessage mail = new MailMessage("projektilibrary@gmail.com", klienti.Email);
                    mail.Subject = "Rezervimi I Librit " + libra.Titulli;
                    mail.Body = "Pershendetje , Ju informojme se librin " + libra.Titulli+ " qe keni rezervuar tashme eshte i lire dhe mund te vini ta merrni Librin";
                    SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
                    smtpClient.Credentials = new System.Net.NetworkCredential()
                    {
                        UserName = "projektilibrary@gmail.com",
                        Password = "projektilibrary123"
                    };
                    smtpClient.EnableSsl = true;
                    smtpClient.Send(mail);
                    r.Aktiv = false;
                    _context.Rezervimi.Update(r);
                    _context.SaveChanges();

                }
            }
       

            return RedirectToAction("Index");
        }


   
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var r = await _context.Huazimi
                .FirstOrDefaultAsync(m => m.id == id);
            if (r == null)
            {
                return NotFound();
            }

            return View(r);
        }

        // POST: HuazimiController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var r = await _context.Huazimi.FindAsync(id);
            _context.Huazimi.Remove(r);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HuazimiExists(int id)
        {
            return _context.Huazimi.Any(e => e.id == id);
        }
    }
}

BOOKS/Views/Huazimi/Create.cshtml
@model BOOKS.Models.Huazimi;

@{
    ViewData["Title"] = "Create";
}

<h2 style="color:white;">Huazo</h2>


<div class="modal-dialog">
    <div class="modal-content">
        <form class="form" asp-action="Create" method="post">
            <div class="modal-header">
                <h4 class="modal-title">Huazo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="window.location='/Huazimi';">&times;</button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Klienti:</label>
                    <select asp-for="Klienti_id" class="form-control" asp-items="@(new SelectList(ViewBag.klientetid,"id","id"))">
                    </select>
                </div>
                <div class="form-group">
                    <label>Libra:</label>
                    <select asp-for="Libra_id" class="form-control" asp-items="@(new SelectList(ViewBag.libraid,"id","id"))">
                    </select>
                </div>
            </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-dark" value="Anulo" onclick="window.location='/Huazimi';">
                    <input type="submit" value="Huazo" class="btn btn-primary" float-right">
                </div>
                
              
            </form>
</div>
</div>

BOOKS/Views/Huazimi/Delete.cshtml
@model BOOKS.Models.Huazimi

@{
    ViewData["Title"] = "Delete";
}

<h2 style="color:white">Delete</h2>


<div class="modal-dialog">
    <div class="modal-content">
        <form class="form" asp-action="Delete" method="post">
            <div class="modal-header">
                <h4 class="modal-title">Are you sure you want to delete this?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="window.location='/huazimi';">&times;</button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Data E Pritjes:</label>
                    <h5 class="form-control">@Html.DisplayFor(model => model.DataPritjes)</h5>
                </div>
                <div class="form-group">
                    <label>Data e Kthimit:</label>
                    <h5 class="form-control">@Html.DisplayFor(model => model.DataKthimit)</h5>
                </div>
                <div class="form-group">
                    <label>Klienti ID:</label>
                    <h5 class="form-control">@Html.DisplayFor(model => model.Klienti_id)</h5>
                </div>
                <div class="form-group">
                    <label>Libra ID:</label>
                    <h5 class="form-control">@Html.DisplayFor(model => model.Libra_id)</h5>
                </div>
                <div class="form-group">
                    <label>Aktiv</label>
                    <h5>@Html.DisplayFor(model => model.Aktiv)</h5>
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn btn-dark" value="Anulo" onclick="window.location='/huazimi';">
                <input type="submit" value="Delete" class="btn btn-danger" float-right">
            </div>
        </form>
    </div>
</div>

BOOKS/Views/Huazimi/Details.cshtml
@model BOOKS.Models.Huazimi
@{
    ViewData["Title"] = "Index";
}
<div>
    <table class="table">
        <tr>
            <td>@Model.id</td>
            <td>@Model.DataPritjes</td>
            <td>@Model.DataKthimit</td>
            <td>@Model.Klienti_id</td>
            <td>@Model.Libra_id</td>
            <td>@Model.Aktiv</td>
        </tr>
    </table>
</div>

BOOKS/Views/Huazimi/Index.cshtml
@using BOOKS.Areas.Identity.Data;
@model PaginatedList<BOOKS.Models.Huazimi>

@{
    ViewData["Title"] = "Index";
}

<title>Index</title>

<!-- Page Heading -->
<h1 style="color:white;">Huazimet</h1>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="float-right">
            <a class="btn btn-primary" asp-controller="Huazimi" asp-action="Create">Huazo</a>
        </div>
        <h6 class="m-0 font-weight-bold text-primary"></h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>DataPritjes</th>
                        <th>DataKthimit</th>
                        <th>Klienti_id</th>
                        <th>Libra_id</th>
                        <th>Aktiv</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>DataPritjes</th>
                        <th>DataKthimit</th>
                        <th>Klienti_id</th>
                        <th>Libra_id</th>
                        <th>Aktiv</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => item.DataPritjes)</td>
                            <td>@Html.DisplayFor(model => item.DataKthimit)</td>
                            <td>@Html.DisplayFor(model => item.Klienti_id)</td>
                            <td>@Html.DisplayFor(model => item.Libra_id)</td>
                            <td>@Html.DisplayFor(model => item.Aktiv)</td>
                            <td>

                                @if (item.Aktiv)
                                {
                                    <a class="btn btn-primary" asp-action="Kthe" asp-route-id="@item.id">Kthe</a>
                                }
                                else
                                {
                                    <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.id })">Delete</a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <div class="pr-4">
        <ul style="display: flex; float:right; list-style: none; border-radius: .35rem">
            <li class="paginate_button page-item previous" id="dataTable_previous">
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   aria-controls="dataTable" data-dt-idx="1"
                   class="btn page-link @prevDisabled">
                    Previous
                </a>
            </li>
            <li class="paginate_button page-item next" id="dataTable_next">
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   aria-controls="dataTable" data-dt-idx="2"
                   class="btn page-link @nextDisabled">
                    Next
                </a>
            </li>
        </ul>
    </div>

</div>